import type { McpServer } from "@/lib/types";
import { applyServerCatalogDefaults } from "@/lib/server-catalog-defaults";
const baseMockServers: McpServer[] = [
    {
        id: "1",
        name: "Linear",
        slug: "linear",
        description: "Manage issues, projects, and cycles from your AI workflows.",
        serverUrl: "https://mcp.linear.app/sse",
        category: "Project Management",
        authType: "oauth",
        tags: ["verified", "official"],
        repoUrl: "https://linear.app/docs/mcp",
        status: "active",
        verificationLevel: "official",
        tools: ["list_issues", "create_issue", "update_issue"],
    },
    {
        id: "2",
        name: "Google Drive",
        slug: "google-drive",
        description: "Search, read, and organize documents in Google Drive.",
        serverUrl: "https://mcp.gdrive.dev/sse",
        category: "Productivity",
        authType: "oauth",
        tags: ["popular"],
        repoUrl: "https://github.com/modelcontextprotocol/servers",
        status: "active",
        verificationLevel: "community",
        tools: ["search_files", "read_file", "create_doc"],
    },
    {
        id: "3",
        name: "Brave Search",
        slug: "brave-search",
        description: "Web and news search API for agent grounding.",
        serverUrl: "https://mcp.brave.com/sse",
        category: "Search",
        authType: "api_key",
        tags: ["search", "web"],
        repoUrl: "https://github.com/modelcontextprotocol/servers",
        status: "active",
        verificationLevel: "partner",
        tools: ["web_search", "news_search"],
    },
    {
        id: "4",
        name: "Apify",
        slug: "apify",
        description: "Run scrapers and data pipelines from MCP-enabled clients.",
        serverUrl: "https://mcp.apify.dev/sse",
        category: "Data",
        authType: "api_key",
        tags: ["automation", "scraping"],
        repoUrl: "https://github.com/modelcontextprotocol/servers",
        status: "active",
        verificationLevel: "community",
        tools: ["run_actor", "get_dataset", "list_actors"],
    },
    {
        id: "5",
        name: "WeatherKit",
        slug: "weatherkit",
        description: "Simple weather retrieval for forecasts and conditions.",
        serverUrl: "https://mcp.weatherkit.dev/sse",
        category: "Utilities",
        authType: "none",
        tags: ["open"],
        status: "active",
        verificationLevel: "community",
        tools: ["get_forecast", "get_current_weather"],
    },
    {
        id: "6",
        name: "Slack",
        slug: "slack",
        description: "Send and query channel messages with workspace auth.",
        serverUrl: "https://mcp.slack.dev/sse",
        category: "Communication",
        authType: "oauth",
        tags: ["team"],
        repoUrl: "https://github.com/modelcontextprotocol/servers",
        status: "active",
        verificationLevel: "official",
        tools: ["list_channels", "send_message", "search_messages"],
    },
    {
        id: "7",
        name: "GitHub",
        slug: "github",
        description: "Access repositories, pull requests, and issues for coding agents.",
        serverUrl: "https://mcp.github.com/sse",
        category: "Developer Tools",
        authType: "oauth",
        tags: ["verified", "dev"],
        repoUrl: "https://github.com/modelcontextprotocol/servers",
        status: "active",
        verificationLevel: "official",
        tools: ["list_repos", "read_file", "create_pr"],
    },
    {
        id: "8",
        name: "Notion",
        slug: "notion",
        description: "Create and update pages/databases from agent flows.",
        serverUrl: "https://mcp.notion.dev/sse",
        category: "Knowledge",
        authType: "oauth",
        tags: ["docs"],
        status: "active",
        verificationLevel: "partner",
        tools: ["search_pages", "create_page", "append_block"],
    },
    {
        id: "9",
        name: "Airtable",
        slug: "airtable",
        description: "Read/write records from Airtable bases with typed operations.",
        serverUrl: "https://mcp.airtable.dev/sse",
        category: "Productivity",
        authType: "oauth",
        tags: ["pending"],
        status: "pending",
        verificationLevel: "community",
        tools: ["list_bases", "get_records", "create_record"],
    },
    {
        id: "10",
        name: "Stripe",
        slug: "stripe",
        description: "Access payments, subscriptions, and customer records from MCP.",
        serverUrl: "https://mcp.stripe.dev/sse",
        category: "Finance",
        authType: "api_key",
        tags: ["pending", "payments"],
        status: "pending",
        verificationLevel: "partner",
        tools: ["list_customers", "create_invoice", "list_subscriptions"],
    },
    {
        id: "11",
        name: "GitLab",
        slug: "gitlab",
        description: "Manage merge requests, issues, and repositories in GitLab.",
        serverUrl: "https://mcp.gitlab.dev/sse",
        category: "Developer Tools",
        authType: "oauth",
        tags: ["git", "devops"],
        status: "active",
        verificationLevel: "partner",
        tools: ["list_projects", "create_issue", "open_merge_request"],
    },
    {
        id: "12",
        name: "Asana",
        slug: "asana",
        description: "Manage tasks and projects in Asana from AI agents.",
        serverUrl: "https://mcp.asana.dev/sse",
        category: "Project Management",
        authType: "oauth",
        tags: ["tasks", "team"],
        status: "active",
        verificationLevel: "official",
        tools: ["list_projects", "create_task", "update_task"],
    },
    {
        id: "13",
        name: "Jira",
        slug: "jira",
        description: "Read and mutate Jira tickets for planning and triage workflows.",
        serverUrl: "https://mcp.jira.dev/sse",
        category: "Project Management",
        authType: "oauth",
        tags: ["issues", "enterprise"],
        status: "active",
        verificationLevel: "official",
        tools: ["list_issues", "create_issue", "transition_issue"],
    },
    {
        id: "14",
        name: "Postgres",
        slug: "postgres",
        description: "Query Postgres databases using controlled read/write operations.",
        serverUrl: "https://mcp.postgres.dev/sse",
        category: "Data",
        authType: "none",
        tags: ["database", "sql"],
        status: "active",
        verificationLevel: "community",
        tools: ["run_query", "describe_table", "list_tables"],
    },
    {
        id: "15",
        name: "Shopify",
        slug: "shopify",
        description: "Operate products, orders, and inventory from Shopify stores.",
        serverUrl: "https://mcp.shopify.dev/sse",
        category: "Commerce",
        authType: "oauth",
        tags: ["ecommerce"],
        status: "active",
        verificationLevel: "partner",
        tools: ["list_products", "create_product", "list_orders"],
    },
    {
        id: "16",
        name: "HubSpot",
        slug: "hubspot",
        description: "Manage CRM entities like contacts, deals, and activities.",
        serverUrl: "https://mcp.hubspot.dev/sse",
        category: "CRM",
        authType: "oauth",
        tags: ["sales", "marketing"],
        status: "active",
        verificationLevel: "partner",
        tools: ["search_contacts", "create_deal", "list_companies"],
    },
    {
        id: "17",
        name: "Trello",
        slug: "trello",
        description: "Create cards and organize boards for lightweight project tracking.",
        serverUrl: "https://mcp.trello.dev/sse",
        category: "Project Management",
        authType: "oauth",
        tags: ["kanban"],
        status: "active",
        verificationLevel: "community",
        tools: ["list_boards", "create_card", "move_card"],
    },
    {
        id: "18",
        name: "Discord",
        slug: "discord",
        description: "Send and read Discord channel messages with bot integrations.",
        serverUrl: "https://mcp.discord.dev/sse",
        category: "Communication",
        authType: "oauth",
        tags: ["chat", "community"],
        status: "active",
        verificationLevel: "community",
        tools: ["list_channels", "send_message", "get_messages"],
    },
    {
        id: "19",
        name: "Figma",
        slug: "figma",
        description: "Access file nodes, comments, and exports from Figma projects.",
        serverUrl: "https://mcp.figma.dev/sse",
        category: "Design",
        authType: "oauth",
        tags: ["ui", "assets"],
        status: "active",
        verificationLevel: "partner",
        tools: ["get_file", "list_comments", "export_nodes"],
    },
    {
        id: "20",
        name: "Sentry",
        slug: "sentry",
        description: "Inspect issues, releases, and alerts from Sentry projects.",
        serverUrl: "https://mcp.sentry.dev/sse",
        category: "Developer Tools",
        authType: "oauth",
        tags: ["observability"],
        status: "active",
        verificationLevel: "official",
        tools: ["list_issues", "get_issue", "list_releases"],
    },
];
export const mockServers: McpServer[] = baseMockServers.map(applyServerCatalogDefaults);
