import type { McpServer } from "@/lib/types";

type ServerCatalogDefaults = {
  repoUrl?: string;
  tools: string[];
};

const catalogDefaultsBySlug: Record<string, ServerCatalogDefaults> = {
  linear: {
    repoUrl: "https://linear.app/docs/mcp",
    tools: [
      "create_attachment",
      "create_comment",
      "create_document",
      "create_issue",
      "create_issue_label",
      "create_milestone",
      "create_project",
      "delete_attachment",
      "extract_images",
      "get_attachment",
      "get_document",
      "get_issue",
      "get_issue_status",
      "get_milestone",
      "get_project",
      "get_team",
      "get_user",
      "list_comments",
      "list_cycles",
      "list_documents",
      "list_issue_labels",
      "list_issue_statuses",
      "list_issues",
      "list_milestones",
      "list_project_labels",
      "list_projects",
      "list_teams",
      "list_users",
      "search_documentation",
      "update_document",
      "update_issue",
      "update_milestone",
      "update_project",
    ],
  },
  "google-drive": {
    repoUrl: "https://developers.google.com/drive/api",
    tools: [
      "search_files",
      "get_file_metadata",
      "read_file",
      "export_file",
      "list_folders",
      "create_folder",
      "upload_file",
      "update_file",
      "move_file",
      "copy_file",
      "delete_file",
      "share_file",
      "list_permissions",
      "revoke_permission",
    ],
  },
  "brave-search": {
    repoUrl: "https://brave.com/search/api/",
    tools: [
      "web_search",
      "news_search",
      "image_search",
      "video_search",
      "local_search",
      "query_suggestions",
      "fetch_result",
      "summarize_results",
    ],
  },
  apify: {
    repoUrl: "https://docs.apify.com/api/v2",
    tools: [
      "list_actors",
      "get_actor",
      "run_actor",
      "get_run",
      "abort_run",
      "list_datasets",
      "get_dataset",
      "get_dataset_items",
      "list_key_value_stores",
      "get_record",
      "set_record",
      "delete_record",
      "list_schedules",
      "create_schedule",
    ],
  },
  weatherkit: {
    repoUrl: "https://weatherkit.apple.com",
    tools: [
      "get_current_weather",
      "get_forecast_daily",
      "get_forecast_hourly",
      "get_weather_alerts",
      "get_air_quality",
      "get_historical_weather",
      "resolve_location",
    ],
  },
  slack: {
    repoUrl: "https://api.slack.com",
    tools: [
      "list_channels",
      "get_channel_info",
      "join_channel",
      "leave_channel",
      "list_members",
      "get_user_profile",
      "send_message",
      "update_message",
      "delete_message",
      "reply_in_thread",
      "add_reaction",
      "remove_reaction",
      "search_messages",
      "list_files",
      "upload_file",
    ],
  },
  github: {
    repoUrl: "https://docs.github.com/en/rest",
    tools: [
      "list_repositories",
      "get_repository",
      "list_branches",
      "list_commits",
      "get_commit",
      "search_code",
      "read_file",
      "create_or_update_file",
      "delete_file",
      "list_issues",
      "create_issue",
      "update_issue",
      "list_pull_requests",
      "create_pull_request",
      "review_pull_request",
      "merge_pull_request",
      "list_workflows",
      "trigger_workflow",
    ],
  },
  notion: {
    repoUrl: "https://developers.notion.com/reference/intro",
    tools: [
      "search_pages",
      "search_databases",
      "get_page",
      "create_page",
      "update_page",
      "archive_page",
      "append_block",
      "list_block_children",
      "query_database",
      "create_database",
      "update_database",
      "create_comment",
    ],
  },
  airtable: {
    repoUrl: "https://airtable.com/developers/web/api/introduction",
    tools: [
      "list_bases",
      "list_tables",
      "list_records",
      "get_record",
      "create_record",
      "update_record",
      "delete_record",
      "upsert_records",
      "list_views",
      "create_table",
      "list_fields",
    ],
  },
  stripe: {
    repoUrl: "https://docs.stripe.com/api",
    tools: [
      "list_customers",
      "create_customer",
      "update_customer",
      "list_products",
      "create_product",
      "list_prices",
      "create_price",
      "create_checkout_session",
      "list_subscriptions",
      "create_subscription",
      "cancel_subscription",
      "list_invoices",
      "create_invoice",
      "finalize_invoice",
      "create_refund",
    ],
  },
  gitlab: {
    repoUrl: "https://docs.gitlab.com/api/",
    tools: [
      "list_projects",
      "get_project",
      "list_branches",
      "create_branch",
      "list_merge_requests",
      "create_merge_request",
      "update_merge_request",
      "merge_merge_request",
      "list_issues",
      "create_issue",
      "update_issue",
      "get_file",
      "commit_file",
      "trigger_pipeline",
    ],
  },
  asana: {
    repoUrl: "https://developers.asana.com/docs",
    tools: [
      "list_workspaces",
      "list_projects",
      "get_project",
      "list_tasks",
      "create_task",
      "update_task",
      "complete_task",
      "add_comment",
      "list_sections",
      "create_section",
      "add_task_to_section",
      "list_users",
    ],
  },
  jira: {
    repoUrl: "https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/",
    tools: [
      "list_projects",
      "get_project",
      "search_issues",
      "get_issue",
      "create_issue",
      "update_issue",
      "transition_issue",
      "add_comment",
      "list_boards",
      "list_sprints",
      "create_sprint",
      "move_issue_to_sprint",
      "list_issue_types",
    ],
  },
  postgres: {
    repoUrl: "https://www.postgresql.org/docs/",
    tools: [
      "list_schemas",
      "list_tables",
      "describe_table",
      "run_query",
      "run_parameterized_query",
      "explain_query",
      "create_table",
      "alter_table",
      "create_index",
      "drop_index",
      "begin_transaction",
      "commit_transaction",
      "rollback_transaction",
    ],
  },
  shopify: {
    repoUrl: "https://shopify.dev/docs/api",
    tools: [
      "list_products",
      "get_product",
      "create_product",
      "update_product",
      "delete_product",
      "list_orders",
      "get_order",
      "fulfill_order",
      "refund_order",
      "list_customers",
      "get_customer",
      "create_discount",
      "list_inventory",
      "update_inventory",
    ],
  },
  hubspot: {
    repoUrl: "https://developers.hubspot.com/docs/api/overview",
    tools: [
      "search_contacts",
      "get_contact",
      "create_contact",
      "update_contact",
      "search_companies",
      "create_company",
      "update_company",
      "search_deals",
      "create_deal",
      "update_deal",
      "list_tickets",
      "create_ticket",
      "associate_records",
    ],
  },
  trello: {
    repoUrl: "https://developer.atlassian.com/cloud/trello/rest/",
    tools: [
      "list_boards",
      "get_board",
      "list_lists",
      "create_list",
      "list_cards",
      "get_card",
      "create_card",
      "update_card",
      "move_card",
      "archive_card",
      "add_comment_to_card",
      "add_member_to_card",
      "list_labels",
      "add_label_to_card",
    ],
  },
  discord: {
    repoUrl: "https://discord.com/developers/docs/intro",
    tools: [
      "list_guilds",
      "list_channels",
      "get_channel",
      "send_message",
      "edit_message",
      "delete_message",
      "add_reaction",
      "remove_reaction",
      "list_members",
      "get_member",
      "create_thread",
      "list_threads",
      "upload_attachment",
    ],
  },
  figma: {
    repoUrl: "https://www.figma.com/developers/api",
    tools: [
      "list_team_projects",
      "list_project_files",
      "get_file",
      "get_file_nodes",
      "list_file_comments",
      "create_comment",
      "get_images",
      "export_nodes",
      "get_styles",
      "get_components",
    ],
  },
  sentry: {
    repoUrl: "https://docs.sentry.io/api/",
    tools: [
      "list_organizations",
      "list_projects",
      "list_issues",
      "get_issue",
      "update_issue",
      "resolve_issue",
      "list_events",
      "get_event",
      "list_releases",
      "get_release",
      "create_release",
      "list_alert_rules",
      "create_alert_rule",
    ],
  },
};

const categoryToolFallbacks: Record<string, string[]> = {
  "project management": [
    "list_projects",
    "get_project",
    "list_tasks",
    "create_task",
    "update_task",
    "add_comment",
  ],
  productivity: [
    "list_items",
    "search_items",
    "get_item",
    "create_item",
    "update_item",
    "delete_item",
  ],
  search: [
    "web_search",
    "news_search",
    "image_search",
    "fetch_result",
    "query_suggestions",
  ],
  data: [
    "list_sources",
    "get_source",
    "run_query",
    "create_record",
    "update_record",
    "delete_record",
  ],
  utilities: [
    "get_status",
    "get_current",
    "get_forecast",
    "resolve_location",
    "run_check",
  ],
  communication: [
    "list_channels",
    "send_message",
    "reply_in_thread",
    "search_messages",
    "list_members",
  ],
  "developer tools": [
    "list_repositories",
    "read_file",
    "create_issue",
    "create_pull_request",
    "list_workflows",
  ],
  knowledge: [
    "search_pages",
    "get_page",
    "create_page",
    "update_page",
    "append_block",
  ],
  finance: [
    "list_customers",
    "create_invoice",
    "list_subscriptions",
    "create_refund",
    "get_balance",
  ],
  commerce: [
    "list_products",
    "create_product",
    "list_orders",
    "update_inventory",
    "create_discount",
  ],
  crm: [
    "search_contacts",
    "create_contact",
    "update_contact",
    "create_deal",
    "list_tickets",
  ],
  design: [
    "list_files",
    "get_file",
    "list_comments",
    "create_comment",
    "export_nodes",
  ],
};

function normalizeToolList(tools: string[]): string[] {
  const unique = new Set<string>();

  for (const tool of tools) {
    const normalized = tool.trim();
    if (normalized) {
      unique.add(normalized);
    }
  }

  return [...unique];
}

export function getServerCatalogDefaults(slug: string): ServerCatalogDefaults | null {
  return catalogDefaultsBySlug[slug] ?? null;
}

export function applyServerCatalogDefaults(mcpServer: McpServer): McpServer {
  const defaults = getServerCatalogDefaults(mcpServer.slug);
  const categoryFallbackTools = categoryToolFallbacks[mcpServer.category.toLowerCase()] ?? [];
  const mergedTools = normalizeToolList([
    ...(defaults?.tools ?? []),
    ...mcpServer.tools,
    ...categoryFallbackTools,
  ]);

  if (!defaults) {
    return {
      ...mcpServer,
      tools: mergedTools,
    };
  }

  return {
    ...mcpServer,
    repoUrl: defaults.repoUrl ?? mcpServer.repoUrl,
    tools: mergedTools,
  };
}
