BOT_NAME = "mcp_scraper"

SPIDER_MODULES = ["mcp_scraper.spiders"]
NEWSPIDER_MODULE = "mcp_scraper.spiders"

ROBOTSTXT_OBEY = True

CONCURRENT_REQUESTS = 8
DOWNLOAD_DELAY = 0.25
RANDOMIZE_DOWNLOAD_DELAY = True

REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"
FEED_EXPORT_ENCODING = "utf-8"
